import 'package:booking_system_flutter/model/category_model.dart';
import 'package:booking_system_flutter/model/dashboard_model.dart';
import 'package:booking_system_flutter/model/service_data_model.dart';
import 'package:booking_system_flutter/model/shop_model.dart';

class DummyDataHelper {
  static DashboardResponse getDummyDashboardData() {
    return DashboardResponse(
      slider: _getDummySliders(),
      promotionalBanner: _getDummyPromotionalBanners(),
      category: _getDummyCategories(),
      service: _getDummyServices(),
      featuredServices: _getDummyFeaturedServices(),
      shops: _getDummyShops(),
      upcomingData: null, // Can be null for demo
      notificationUnreadCount: 0,
      isEmailVerified: 1,
    );
  }

  static List<SliderModel> _getDummySliders() {
    return [
      SliderModel(
        id: 1,
        title: "Professional Home Services",
        description: "Get the best services for your home",
        sliderImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800",
        status: 1,
        type: "service",
        typeId: 1,
        serviceName: "Home Cleaning",
      ),
      SliderModel(
        id: 2,
        title: "Expert Handyman Services",
        description: "Quality repairs and maintenance",
        sliderImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800",
        status: 1,
        type: "service",
        typeId: 2,
        serviceName: "Handyman",
      ),
      SliderModel(
        id: 3,
        title: "Plumbing Solutions",
        description: "Fast and reliable plumbing services",
        sliderImage: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800",
        status: 1,
        type: "service",
        typeId: 3,
        serviceName: "Plumbing",
      ),
    ];
  }

  static List<PromotionalBannerModel> _getDummyPromotionalBanners() {
    return [
      PromotionalBannerModel(
        id: 1,
        title: "Special Offer",
        description: "Get 20% off on all services",
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
        bannerType: "service",
        serviceId: 1,
        serviceName: "Home Cleaning",
      ),
    ];
  }

  /// Generate dummy categories with Material Icons instead of images
  /// Returns a list of categories with icon names for display
  static List<CategoryData> _getDummyCategories() {
    return [
      CategoryData(
        id: 1,
        name: "Household",
        categoryImage: "home", // Material Icon name
        description: "Professional household services",
        status: 1,
        isFeatured: 1,
        services: 25,
        color: "#95E1D3", // Light green
      ),
      CategoryData(
        id: 2,
        name: "Cooking",
        categoryImage: "restaurant", // Material Icon name
        description: "Expert cooking services",
        status: 1,
        isFeatured: 1,
        services: 18,
        color: "#95E1D3", // Light green
      ),
      CategoryData(
        id: 3,
        name: "Caretaker",
        categoryImage: "person", // Material Icon name
        description: "Professional caretaker services",
        status: 1,
        isFeatured: 1,
        services: 15,
        color: "#95E1D3", // Light green
      ),
      CategoryData(
        id: 4,
        name: "Special Occasion Helper",
        categoryImage: "celebration", // Material Icon name
        description: "Helpers for special occasions",
        status: 1,
        isFeatured: 1,
        services: 12,
        color: "#95E1D3", // Light green
      ),
      CategoryData(
        id: 5,
        name: "Cleaning",
        categoryImage: "cleaning_services", // Material Icon name
        description: "Professional cleaning services",
        status: 1,
        isFeatured: 1,
        services: 20,
        color: "#4ECDC4",
      ),
      CategoryData(
        id: 6,
        name: "Plumbing",
        categoryImage: "plumbing", // Material Icon name
        description: "Expert plumbing solutions",
        status: 1,
        isFeatured: 1,
        services: 15,
        color: "#4ECDC4",
      ),
      CategoryData(
        id: 7,
        name: "Electrical",
        categoryImage: "electrical_services", // Material Icon name
        description: "Electrical repairs and installations",
        status: 1,
        isFeatured: 1,
        services: 12,
        color: "#FFE66D",
      ),
      CategoryData(
        id: 8,
        name: "Painting",
        categoryImage: "format_paint", // Material Icon name
        description: "Interior and exterior painting",
        status: 1,
        isFeatured: 0,
        services: 10,
        color: "#95E1D3",
      ),
      CategoryData(
        id: 9,
        name: "Carpentry",
        categoryImage: "carpenter", // Material Icon name
        description: "Custom carpentry work",
        status: 1,
        isFeatured: 0,
        services: 8,
        color: "#F38181",
      ),
      CategoryData(
        id: 10,
        name: "Gardening",
        categoryImage: "yard", // Material Icon name
        description: "Landscaping and gardening",
        status: 1,
        isFeatured: 0,
        services: 14,
        color: "#AAE3E2",
      ),
      CategoryData(
        id: 11,
        name: "AC Repair",
        categoryImage: "ac_unit", // Material Icon name
        description: "Air conditioning repair and maintenance",
        status: 1,
        isFeatured: 0,
        services: 9,
        color: "#4ECDC4",
      ),
      CategoryData(
        id: 12,
        name: "Appliance Repair",
        categoryImage: "build", // Material Icon name
        description: "Home appliance repair services",
        status: 1,
        isFeatured: 0,
        services: 11,
        color: "#FFE66D",
      ),
      CategoryData(
        id: 13,
        name: "Pest Control",
        categoryImage: "bug_report", // Material Icon name
        description: "Professional pest control services",
        status: 1,
        isFeatured: 0,
        services: 7,
        color: "#F38181",
      ),
      CategoryData(
        id: 14,
        name: "Moving & Packing",
        categoryImage: "local_shipping", // Material Icon name
        description: "Moving and packing services",
        status: 1,
        isFeatured: 0,
        services: 13,
        color: "#AAE3E2",
      ),
      CategoryData(
        id: 15,
        name: "Laundry",
        categoryImage: "local_laundry_service", // Material Icon name
        description: "Laundry and dry cleaning services",
        status: 1,
        isFeatured: 0,
        services: 16,
        color: "#95E1D3",
      ),
      CategoryData(
        id: 16,
        name: "Beauty & Spa",
        categoryImage: "spa", // Material Icon name
        description: "Beauty and spa services",
        status: 1,
        isFeatured: 0,
        services: 19,
        color: "#FF6B6B",
      ),
    ];
  }

  /// Generate dummy services with more content for scrollability
  static List<ServiceData> _getDummyServices() {
    return [
      ServiceData(
        id: 1,
        name: "Household Cleaning Service",
        categoryId: 1,
        categoryName: "Household",
        providerId: 1,
        providerName: "CleanPro Services",
        providerImage: "https://i.pravatar.cc/150?img=12",
        price: 150.0,
        discount: 10.0,
        duration: "3 hours",
        description: "Comprehensive deep cleaning for your entire home",
        status: 1,
        isFeatured: 0,
        totalRating: 4.5,
        totalReview: 120,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 2,
        name: "Professional Cooking Service",
        categoryId: 2,
        categoryName: "Cooking",
        providerId: 2,
        providerName: "Chef Master",
        providerImage: "https://i.pravatar.cc/150?img=13",
        price: 200.0,
        discount: 15.0,
        duration: "4 hours",
        description: "Expert cooking services for your special occasions",
        status: 1,
        isFeatured: 0,
        totalRating: 4.8,
        totalReview: 95,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 3,
        name: "Elderly Caretaker Service",
        categoryId: 3,
        categoryName: "Caretaker",
        providerId: 3,
        providerName: "Care Plus",
        providerImage: "https://i.pravatar.cc/150?img=14",
        price: 180.0,
        discount: 0.0,
        duration: "8 hours",
        description: "Professional caretaker services for elderly care",
        status: 1,
        isFeatured: 0,
        totalRating: 4.7,
        totalReview: 78,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 4,
        name: "Event Planning Helper",
        categoryId: 4,
        categoryName: "Special Occasion Helper",
        providerId: 4,
        providerName: "Event Masters",
        providerImage: "https://i.pravatar.cc/150?img=15",
        price: 250.0,
        discount: 20.0,
        duration: "6 hours",
        description: "Complete event planning and management services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.9,
        totalReview: 156,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 5,
        name: "Deep Home Cleaning",
        categoryId: 5,
        categoryName: "Cleaning",
        providerId: 5,
        providerName: "Sparkle Clean",
        providerImage: "https://i.pravatar.cc/150?img=16",
        price: 120.0,
        discount: 5.0,
        duration: "2.5 hours",
        description: "Thorough deep cleaning service for your home",
        status: 1,
        isFeatured: 0,
        totalRating: 4.6,
        totalReview: 65,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 6,
        name: "Plumbing Repair Service",
        categoryId: 6,
        categoryName: "Plumbing",
        providerId: 6,
        providerName: "FixIt Plumbing",
        providerImage: "https://i.pravatar.cc/150?img=17",
        price: 100.0,
        discount: 0.0,
        duration: "2 hours",
        description: "Professional plumbing repair and maintenance",
        status: 1,
        isFeatured: 0,
        totalRating: 4.7,
        totalReview: 89,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 7,
        name: "Electrical Installation",
        categoryId: 7,
        categoryName: "Electrical",
        providerId: 7,
        providerName: "Safe Electric",
        providerImage: "https://i.pravatar.cc/150?img=18",
        price: 180.0,
        discount: 10.0,
        duration: "3 hours",
        description: "Safe and professional electrical installation",
        status: 1,
        isFeatured: 0,
        totalRating: 4.8,
        totalReview: 112,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 8,
        name: "Interior Painting",
        categoryId: 8,
        categoryName: "Painting",
        providerId: 8,
        providerName: "Color Masters",
        providerImage: "https://i.pravatar.cc/150?img=19",
        price: 300.0,
        discount: 25.0,
        duration: "1 day",
        description: "Professional interior painting services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.5,
        totalReview: 67,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 9,
        name: "Custom Carpentry Work",
        categoryId: 9,
        categoryName: "Carpentry",
        providerId: 9,
        providerName: "Wood Crafts",
        providerImage: "https://i.pravatar.cc/150?img=20",
        price: 250.0,
        discount: 15.0,
        duration: "1 day",
        description: "Custom carpentry and woodwork services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.9,
        totalReview: 134,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 10,
        name: "Garden Landscaping",
        categoryId: 10,
        categoryName: "Gardening",
        providerId: 10,
        providerName: "Green Thumb",
        providerImage: "https://i.pravatar.cc/150?img=21",
        price: 200.0,
        discount: 0.0,
        duration: "4 hours",
        description: "Professional garden landscaping and maintenance",
        status: 1,
        isFeatured: 0,
        totalRating: 4.6,
        totalReview: 98,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 11,
        name: "AC Repair & Service",
        categoryId: 11,
        categoryName: "AC Repair",
        providerId: 11,
        providerName: "Cool Air Pro",
        providerImage: "https://i.pravatar.cc/150?img=22",
        price: 150.0,
        discount: 10.0,
        duration: "2 hours",
        description: "AC repair, service and maintenance",
        status: 1,
        isFeatured: 0,
        totalRating: 4.7,
        totalReview: 76,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 12,
        name: "Appliance Repair",
        categoryId: 12,
        categoryName: "Appliance Repair",
        providerId: 12,
        providerName: "Fix All Appliances",
        providerImage: "https://i.pravatar.cc/150?img=23",
        price: 120.0,
        discount: 5.0,
        duration: "2 hours",
        description: "Home appliance repair and maintenance",
        status: 1,
        isFeatured: 0,
        totalRating: 4.5,
        totalReview: 54,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 13,
        name: "Pest Control Service",
        categoryId: 13,
        categoryName: "Pest Control",
        providerId: 13,
        providerName: "Pest Free",
        providerImage: "https://i.pravatar.cc/150?img=24",
        price: 100.0,
        discount: 0.0,
        duration: "1.5 hours",
        description: "Professional pest control and extermination",
        status: 1,
        isFeatured: 0,
        totalRating: 4.8,
        totalReview: 143,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 14,
        name: "Moving & Packing Service",
        categoryId: 14,
        categoryName: "Moving & Packing",
        providerId: 14,
        providerName: "Move Easy",
        providerImage: "https://i.pravatar.cc/150?img=25",
        price: 400.0,
        discount: 30.0,
        duration: "1 day",
        description: "Complete moving and packing services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.6,
        totalReview: 87,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 15,
        name: "Laundry Service",
        categoryId: 15,
        categoryName: "Laundry",
        providerId: 15,
        providerName: "Fresh Laundry",
        providerImage: "https://i.pravatar.cc/150?img=26",
        price: 50.0,
        discount: 0.0,
        duration: "1 hour",
        description: "Professional laundry and dry cleaning",
        status: 1,
        isFeatured: 0,
        totalRating: 4.7,
        totalReview: 92,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 16,
        name: "Beauty & Spa Service",
        categoryId: 16,
        categoryName: "Beauty & Spa",
        providerId: 16,
        providerName: "Beauty Salon",
        providerImage: "https://i.pravatar.cc/150?img=27",
        price: 180.0,
        discount: 20.0,
        duration: "2 hours",
        description: "Professional beauty and spa services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.9,
        totalReview: 167,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
    ];
  }

  /// Generate dummy featured services
  static List<ServiceData> _getDummyFeaturedServices() {
    return [
      ServiceData(
        id: 17,
        name: "Premium Household Service",
        categoryId: 1,
        categoryName: "Household",
        providerId: 1,
        providerName: "Elite Services",
        providerImage: "https://i.pravatar.cc/150?img=12",
        price: 300.0,
        discount: 25.0,
        duration: "6 hours",
        description: "Premium household services with eco-friendly products",
        status: 1,
        isFeatured: 1,
        totalRating: 5.0,
        totalReview: 200,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 18,
        name: "Gourmet Cooking Service",
        categoryId: 2,
        categoryName: "Cooking",
        providerId: 2,
        providerName: "Master Chef",
        providerImage: "https://i.pravatar.cc/150?img=13",
        price: 350.0,
        discount: 30.0,
        duration: "5 hours",
        description: "Gourmet cooking service for special occasions",
        status: 1,
        isFeatured: 1,
        totalRating: 4.9,
        totalReview: 178,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 19,
        name: "Complete Plumbing Service",
        categoryId: 6,
        categoryName: "Plumbing",
        providerId: 6,
        providerName: "Master Plumbers",
        providerImage: "https://i.pravatar.cc/150?img=17",
        price: 220.0,
        discount: 15.0,
        duration: "4 hours",
        description: "Complete plumbing inspection and repair service",
        status: 1,
        isFeatured: 1,
        totalRating: 4.8,
        totalReview: 156,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
      ServiceData(
        id: 20,
        name: "Full House Painting",
        categoryId: 8,
        categoryName: "Painting",
        providerId: 8,
        providerName: "Color Masters",
        providerImage: "https://i.pravatar.cc/150?img=19",
        price: 800.0,
        discount: 50.0,
        duration: "2 days",
        description: "Professional interior and exterior painting",
        status: 1,
        isFeatured: 1,
        totalRating: 4.7,
        totalReview: 98,
        type: "fixed",
        serviceAttachments: [],
        isFavourite: 0,
      ),
    ];
  }

  static List<ShopModel> _getDummyShops() {
    return [
      ShopModel(
        id: 1,
        name: "Home Services Hub",
        address: "123 Main Street, City Center",
        cityName: "New York",
        stateName: "NY",
        countryName: "USA",
        contactNumber: "+1 234-567-8900",
        email: "info@homeserviceshub.com",
        shopImage: [
          "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400",
        ],
        providerId: 1,
        providerName: "John Smith",
        providerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        serviceCount: 25,
        providerServiceRating: 4.8,
        isFavourite: 0,
        latitude: 40.7128,
        longitude: -74.0060,
        shopStartTime: "09:00",
        shopEndTime: "18:00",
      ),
      ShopModel(
        id: 2,
        name: "Fix It Fast",
        address: "456 Oak Avenue, Downtown",
        cityName: "Los Angeles",
        stateName: "CA",
        countryName: "USA",
        contactNumber: "+1 234-567-8901",
        email: "contact@fixitfast.com",
        shopImage: [
          "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
        ],
        providerId: 2,
        providerName: "Sarah Johnson",
        providerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        serviceCount: 18,
        providerServiceRating: 4.9,
        isFavourite: 0,
        latitude: 34.0522,
        longitude: -118.2437,
        shopStartTime: "08:00",
        shopEndTime: "17:00",
      ),
      ShopModel(
        id: 3,
        name: "Elite Handyman Services",
        address: "789 Pine Road, Uptown",
        cityName: "Chicago",
        stateName: "IL",
        countryName: "USA",
        contactNumber: "+1 234-567-8902",
        email: "hello@elitehandyman.com",
        shopImage: [
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
        ],
        providerId: 3,
        providerName: "Mike Davis",
        providerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        serviceCount: 30,
        providerServiceRating: 4.7,
        isFavourite: 0,
        latitude: 41.8781,
        longitude: -87.6298,
        shopStartTime: "07:00",
        shopEndTime: "19:00",
      ),
    ];
  }
}

