import 'package:booking_system_flutter/model/category_model.dart';
import 'package:booking_system_flutter/model/dashboard_model.dart';
import 'package:booking_system_flutter/model/service_data_model.dart';
import 'package:booking_system_flutter/model/shop_model.dart';

class DummyDataHelper {
  static DashboardResponse getDummyDashboardData() {
    return DashboardResponse(
      slider: _getDummySliders(),
      promotionalBanner: _getDummyPromotionalBanners(),
      category: _getDummyCategories(),
      service: _getDummyServices(),
      featuredServices: _getDummyFeaturedServices(),
      shops: _getDummyShops(),
      upcomingData: null, // Can be null for demo
      notificationUnreadCount: 0,
      isEmailVerified: 1,
    );
  }

  static List<SliderModel> _getDummySliders() {
    return [
      SliderModel(
        id: 1,
        title: "Professional Home Services",
        description: "Get the best services for your home",
        sliderImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800",
        status: 1,
        type: "service",
        typeId: 1,
        serviceName: "Home Cleaning",
      ),
      SliderModel(
        id: 2,
        title: "Expert Handyman Services",
        description: "Quality repairs and maintenance",
        sliderImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800",
        status: 1,
        type: "service",
        typeId: 2,
        serviceName: "Handyman",
      ),
      SliderModel(
        id: 3,
        title: "Plumbing Solutions",
        description: "Fast and reliable plumbing services",
        sliderImage: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800",
        status: 1,
        type: "service",
        typeId: 3,
        serviceName: "Plumbing",
      ),
    ];
  }

  static List<PromotionalBannerModel> _getDummyPromotionalBanners() {
    return [
      PromotionalBannerModel(
        id: 1,
        title: "Special Offer",
        description: "Get 20% off on all services",
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
        bannerType: "service",
        serviceId: 1,
        serviceName: "Home Cleaning",
      ),
    ];
  }

  static List<CategoryData> _getDummyCategories() {
    return [
      CategoryData(
        id: 1,
        name: "Cleaning",
        categoryImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
        description: "Professional cleaning services",
        status: 1,
        isFeatured: 1,
        services: 15,
        color: "#FF6B6B",
      ),
      CategoryData(
        id: 2,
        name: "Plumbing",
        categoryImage: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400",
        description: "Expert plumbing solutions",
        status: 1,
        isFeatured: 1,
        services: 12,
        color: "#4ECDC4",
      ),
      CategoryData(
        id: 3,
        name: "Electrical",
        categoryImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400",
        description: "Electrical repairs and installations",
        status: 1,
        isFeatured: 1,
        services: 10,
        color: "#FFE66D",
      ),
      CategoryData(
        id: 4,
        name: "Painting",
        categoryImage: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400",
        description: "Interior and exterior painting",
        status: 1,
        isFeatured: 0,
        services: 8,
        color: "#95E1D3",
      ),
      CategoryData(
        id: 5,
        name: "Carpentry",
        categoryImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
        description: "Custom carpentry work",
        status: 1,
        isFeatured: 0,
        services: 6,
        color: "#F38181",
      ),
      CategoryData(
        id: 6,
        name: "Gardening",
        categoryImage: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
        description: "Landscaping and gardening",
        status: 1,
        isFeatured: 0,
        services: 9,
        color: "#AAE3E2",
      ),
    ];
  }

  static List<ServiceData> _getDummyServices() {
    return [
      ServiceData(
        id: 1,
        name: "Deep Home Cleaning",
        categoryId: 1,
        categoryName: "Cleaning",
        providerId: 1,
        providerName: "CleanPro Services",
        providerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        price: 150.0,
        discount: 10.0,
        duration: "3 hours",
        description: "Comprehensive deep cleaning for your entire home",
        status: 1,
        isFeatured: 0,
        totalRating: 4.5,
        totalReview: 120,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 2,
        name: "Kitchen Deep Clean",
        categoryId: 1,
        categoryName: "Cleaning",
        providerId: 2,
        providerName: "Sparkle Clean",
        providerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        price: 80.0,
        discount: 0.0,
        duration: "2 hours",
        description: "Thorough kitchen cleaning and sanitization",
        status: 1,
        isFeatured: 0,
        totalRating: 4.8,
        totalReview: 95,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 3,
        name: "Bathroom Cleaning",
        categoryId: 1,
        categoryName: "Cleaning",
        providerId: 3,
        providerName: "Fresh Clean Co",
        providerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        price: 60.0,
        discount: 5.0,
        duration: "1.5 hours",
        description: "Complete bathroom cleaning and disinfection",
        status: 1,
        isFeatured: 0,
        totalRating: 4.7,
        totalReview: 78,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 4,
        name: "Leak Repair",
        categoryId: 2,
        categoryName: "Plumbing",
        providerId: 4,
        providerName: "FixIt Plumbing",
        providerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        price: 120.0,
        discount: 0.0,
        duration: "2 hours",
        description: "Professional leak detection and repair",
        status: 1,
        isFeatured: 0,
        totalRating: 4.6,
        totalReview: 65,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 5,
        name: "Electrical Wiring",
        categoryId: 3,
        categoryName: "Electrical",
        providerId: 5,
        providerName: "Safe Electric",
        providerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        price: 200.0,
        discount: 15.0,
        duration: "4 hours",
        description: "Safe and professional electrical wiring services",
        status: 1,
        isFeatured: 0,
        totalRating: 4.9,
        totalReview: 142,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400",
        ],
        isFavourite: 0,
      ),
    ];
  }

  static List<ServiceData> _getDummyFeaturedServices() {
    return [
      ServiceData(
        id: 6,
        name: "Premium Home Cleaning",
        categoryId: 1,
        categoryName: "Cleaning",
        providerId: 1,
        providerName: "Elite Clean Services",
        providerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        price: 250.0,
        discount: 20.0,
        duration: "5 hours",
        description: "Premium deep cleaning with eco-friendly products",
        status: 1,
        isFeatured: 1,
        totalRating: 5.0,
        totalReview: 200,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 7,
        name: "Complete Plumbing Service",
        categoryId: 2,
        categoryName: "Plumbing",
        providerId: 4,
        providerName: "Master Plumbers",
        providerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        price: 180.0,
        discount: 10.0,
        duration: "3 hours",
        description: "Complete plumbing inspection and repair",
        status: 1,
        isFeatured: 1,
        totalRating: 4.8,
        totalReview: 156,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400",
        ],
        isFavourite: 0,
      ),
      ServiceData(
        id: 8,
        name: "Full House Painting",
        categoryId: 4,
        categoryName: "Painting",
        providerId: 6,
        providerName: "Color Masters",
        providerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        price: 800.0,
        discount: 50.0,
        duration: "2 days",
        description: "Professional interior and exterior painting",
        status: 1,
        isFeatured: 1,
        totalRating: 4.7,
        totalReview: 98,
        type: "fixed",
        serviceAttachments: [
          "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400",
        ],
        isFavourite: 0,
      ),
    ];
  }

  static List<ShopModel> _getDummyShops() {
    return [
      ShopModel(
        id: 1,
        name: "Home Services Hub",
        address: "123 Main Street, City Center",
        cityName: "New York",
        stateName: "NY",
        countryName: "USA",
        contactNumber: "+1 234-567-8900",
        email: "info@homeserviceshub.com",
        shopImage: [
          "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400",
        ],
        providerId: 1,
        providerName: "John Smith",
        providerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        serviceCount: 25,
        providerServiceRating: 4.8,
        isFavourite: 0,
        latitude: 40.7128,
        longitude: -74.0060,
        shopStartTime: "09:00",
        shopEndTime: "18:00",
      ),
      ShopModel(
        id: 2,
        name: "Fix It Fast",
        address: "456 Oak Avenue, Downtown",
        cityName: "Los Angeles",
        stateName: "CA",
        countryName: "USA",
        contactNumber: "+1 234-567-8901",
        email: "contact@fixitfast.com",
        shopImage: [
          "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
        ],
        providerId: 2,
        providerName: "Sarah Johnson",
        providerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        serviceCount: 18,
        providerServiceRating: 4.9,
        isFavourite: 0,
        latitude: 34.0522,
        longitude: -118.2437,
        shopStartTime: "08:00",
        shopEndTime: "17:00",
      ),
      ShopModel(
        id: 3,
        name: "Elite Handyman Services",
        address: "789 Pine Road, Uptown",
        cityName: "Chicago",
        stateName: "IL",
        countryName: "USA",
        contactNumber: "+1 234-567-8902",
        email: "hello@elitehandyman.com",
        shopImage: [
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
        ],
        providerId: 3,
        providerName: "Mike Davis",
        providerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        serviceCount: 30,
        providerServiceRating: 4.7,
        isFavourite: 0,
        latitude: 41.8781,
        longitude: -87.6298,
        shopStartTime: "07:00",
        shopEndTime: "19:00",
      ),
    ];
  }
}

